### ISSUE TITLE
grain init crashes when grain ref has no provider

### ISSUE THREAD

**Issue by Licenser** [SpaceTime-IoT/erleans#12]
verify_etag

erlans_grain (236) calls:
```erl
             {CbState2, ETag1} = verify_etag(CbModule, Id, Provider, ETag, CbState1),
```
if the grain either has no `provider` the variable `Provider` is bound to undefined, however verify_etag calls `Provider:...()` even if no provider is provided.

**Comment by tsloughter** [comment]
Thanks. I do want it to be that you can run a grain stateful grain with no state (just never return `save`). I think for this it just needs to match on `undefined` in `verify_etag` and not use `Provider`. Can patch this shortly.

**Comment by tsloughter** [comment]
Wait no, I had also thought that not defining behaviour functions like `provider` would simply mean "use the default"... But then you will always have to have a provider because it must insert the grain to the storage through it.

**Comment by Licenser** [comment]
I'm going to be in the corner over there pretending I understand what you say ;) it sounds good?

Baiscally, the problem was caused by `provider/0` not being exprted, not sure what the expected behaviour of that should be but I'm pretty sure crashing in `verify_etag` is not not.

I could see:
1) crashing trying to access `provider`
2) not crashing and doeing something else?

**Comment by tsloughter** [comment]
You are right, the current behavior is definitely wrong. The question is should it accept not being able to save a "stateful" grain or should the lack of exporting `provider/0` signal that you want to use the configured `default_provider`, allowing the grain to not be tied to any particular data store.

Eh, really the question is, should a non-stateless grain be able to activate without a backing datastore.

I'd like the resolving of what provider to use be done with the steps:

* Is `provider/0` exported?
* No, then is the `<grain name>` listed in the configuration list of `providers`? (ex, `{erleans, [{grain_provider, [{test_grain, postgres_provider}]}]}`)
* No, then what is `default_provider` configured as?

This way different users are able to configure the same grain to use different backends, but not ony by falling back to the default provider.

**Comment by Licenser** [comment]
Personally I feel enforcing provider would be nice. I know that's a lot about taste but I always find it confusing when there are multiple ways to configure something instead of a single one. Especially implicit ones instead of explicit ones. Other then my personal distaste for choice, the idea sounds very reasonable ;)
