### ISSUE TITLE
Timers

### ISSUE THREAD

**Issue by tsloughter** [SpaceTime-IoT/erleans#24]
Timers are basically the same as `erlang:start_timer`. They are only active during activation they are created during.

**Comment by tsloughter** [comment]
I was considering if we could just leave it to `start_timer` and call it "done". But orleans timers are actually continual, http://dotnet.github.io/orleans/Documentation/Advanced-Concepts/Timers-and-Reminders.html

So I think it needs a `erleans_grain:start_timer` that takes a `Period` and `DueTime`. 

I don't know why in the Orleans case they do:

> Note however, asyncCallback invocations are not delivered as messages and are thus not subject to message interleaving semantics. This means that invocations of asyncCallback should be considered to behave as if running on a reentrant grain with respect to other messages to that grain

We may be fine just doing it as a message to the grain like `erlang:start_timer/send_after` but I'd like to be sure there isn't some advantage for the use cases of timers being done the Orleans way that we'd lose... 

I guess I may need to find someone who actually develops with Orleans :)

**Comment by tsloughter** [comment]
Maybe the point is to not let another message being handled delay the firing of a timer. Of course then the timer handler can't update the state of the grain and not sure what to pass it as the state when it is called if that is the case.

**Comment by evanmcc** [comment]
Yeah, I am not sure we can support the semantics as they are in Orleans, since BEAM won't even let that happen.  It may be that we want to have two behaviors here: a new activation for a stateless grain, and a message sent to a stateful grain.

**Comment by evanmcc** [comment]
Also mentioned by @tsloughter in chat: "spawn separate processes and run a callback".  This could be an appealing model, as you could get timely action and if needed the callback could send a message to the grain for a state update.

**Comment by mrallen1** [comment]
@tsloughter The Orleans devs have been amazingly gracious to questions if you want to open an issue on the [github repo](https://github.com/dotnet/orleans)

**Comment by tsloughter** [comment]
Ah cool, thanks @mrallen1 . I know some projects don't even like you asking questions about your problems running their project if it isn't a definite bug, let alone asking general questions to help with a clone :)

Might also be interesting to look at and ping those working on https://github.com/OrleansContrib/Orleankka

**Comment by evanmcc** [comment]
Orleans timers docs for reference: http://dotnet.github.io/orleans/Documentation/Advanced-Concepts/Timers-and-Reminders.html
